// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID  int64              `json:"account_id"`
	Username   string             `json:"username"`
	Password   string             `json:"password"`
	Balance    int64              `json:"balance"`
	CreateTime pgtype.Timestamptz `json:"create_time"`
	ExpireTime pgtype.Timestamptz `json:"expire_time"`
	Privilege  string             `json:"privilege"`
}

type Deposit struct {
	DepositID         int64  `json:"deposit_id"`
	TransactionDigest string `json:"transaction_digest"`
	Epoch             int64  `json:"epoch"`
	AccountID         int64  `json:"account_id"`
}

type ProcessingWithdrawal struct {
	ProcessingWithdrawalID int64              `json:"processing_withdrawal_id"`
	TransactionDigest      string             `json:"transaction_digest"`
	TransactionBytesBase64 string             `json:"transaction_bytes_base64"`
	TotalPriorityFee       int64              `json:"total_priority_fee"`
	WithdrawalStatus       string             `json:"withdrawal_status"`
	CreateTime             pgtype.Timestamptz `json:"create_time"`
}

type Withdrawal struct {
	WithdrawalID           int64              `json:"withdrawal_id"`
	AccountID              int64              `json:"account_id"`
	WithdrawAddress        []byte             `json:"withdraw_address"`
	Amount                 int64              `json:"amount"`
	PriorityFee            int64              `json:"priority_fee"`
	ProcessingWithdrawalID pgtype.Int8        `json:"processing_withdrawal_id"`
	CreateTime             pgtype.Timestamptz `json:"create_time"`
}
