// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddDepositRecord(ctx context.Context, arg AddDepositRecordParams) (Deposit, error)
	CancelWithdrawalById(ctx context.Context, withdrawalID int64) (CancelWithdrawalByIdRow, error)
	ChangeBalance(ctx context.Context, arg ChangeBalanceParams) (Account, error)
	ChangeBalanceByUsername(ctx context.Context, arg ChangeBalanceByUsernameParams) (Account, error)
	// 'processing' withdrawals must wait being marked to avoid losing money
	CleanOldWithdrawals(ctx context.Context, cleanTime pgtype.Timestamptz) ([]ProcessingWithdrawal, error)
	DeleteInvalidAccounts(ctx context.Context) ([]int64, error)
	GetAccount(ctx context.Context, username string) (Account, error)
	ListProcessingWithdrawals(ctx context.Context, arg ListProcessingWithdrawalsParams) ([]ProcessingWithdrawal, error)
	ListWithdrawals(ctx context.Context, arg ListWithdrawalsParams) ([]Withdrawal, error)
	ProcessWithdrawals(ctx context.Context, arg ProcessWithdrawalsParams) ([]Withdrawal, error)
	QueryBalance(ctx context.Context, accountID int64) (Account, error)
	QueryBalanceForShare(ctx context.Context, accountID int64) (Account, error)
	SelectCandidateWithdrawals(ctx context.Context, retrieveCount int32) ([]Withdrawal, error)
	SetWithdrawalBatch(ctx context.Context, arg SetWithdrawalBatchParams) (ProcessingWithdrawal, error)
	SetWithdrawalSuccess(ctx context.Context, transactionDigest string) (ProcessingWithdrawal, error)
	StartWithdrawal(ctx context.Context, arg StartWithdrawalParams) (Withdrawal, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
