volumes:
  postgres-data:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PATH=/go/bin:/workspaces/prex/bin:/workspaces/prex/scripts:${PATH}
      - GOPATH=/go
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8000:8000
    volumes:
      - ..:/workspaces/prex:consistent
    command: sleep infinity
    working_dir: /workspaces/prex

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest
