name: Run Tests
on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: cat .env.example > $GITHUB_ENV

      - name: Set writable GOPATH
        run: |
          mkdir -p $HOME/go
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV


      - name: Run unit tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: go run github.com/onsi/ginkgo/v2/ginkgo internal/*

      - name: Run API tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bash scripts/api-tests.sh
