name: Run Tests
on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set env
        run: cat .env.example > $GITHUB_ENV

      - name: Set writable GOPATH
        run: |
          mkdir -p /tmp/go
          echo "GOPATH=/tmp/go" >> $GITHUB_ENV
          echo "GOCACHE=/tmp/go/cache" >> $GITHUB_ENV
          echo "PATH=/tmp/go/bin:$PATH" >> $GITHUB_ENV

      - name: Run unit tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: sudo mkdir -p /home/runner && chown -R runner:runner /home/runner && go run github.com/onsi/ginkgo/v2/ginkgo internal/*

      - name: Run API tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: sudo mkdir -p /home/runner && chown -R runner:runner /home/runner && bash scripts/api-tests.sh
